server:
  port: 8097


spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  output:
    ansi:
      enabled: always

  #### database ??

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/novelboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  thymeleaf:
    cache: false
  jpa:
    open-in-view: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update #update
    properties:
      hibernate:
        format_sql: true
        show-sql: true
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB

#### log ??  fatal > error > warn > info > debug
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # ???? ????.